version: '3.8'

services:

  reese-redis:
    image: "bitnami/redis:5.0.4"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "reese_redis_data:/bitnami/redis/data"

  reese-api:
    build: app
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://:password123@reese-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:password123@reese-redis:6379/0
    depends_on:
      - reese-redis

  reese-worker:
    build: ./app
    command: celery worker --app=celery_worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://:password123@reese-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:password123@reese-redis:6379/0
    depends_on:
      - reese-api
      - reese-redis

  reese-flower:
    build: ./app
    command: flower --port=5555 --broker=redis://:password123@reese-redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://:password123@reese-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:password123@reese-redis:6379/0
    depends_on:
      - reese-api
      - reese-redis
      - reese-worker

volumes:
  reese_redis_data:
    driver: local
